### ISSUE TITLE
Commits messages

### ISSUE THREAD

**Issue by tOOnPT** [tostasqb/tracker#10]
Make use of commits is good but why only a message on those commits. Why not descriptions too?

**Comment by tostasqb** [comment]
I don't have anything against descriptions on commits. I used to use it when committing some major version to describe some of the main impacts and feature releases of that version. For the majority of the cases though I tend to be satisfied with a one line commit.

**Comment by tOOnPT** [comment]
One line description will say to you what's about the commit but nothing else. If my project has one, two, three years (or even just some months) I can't now more that. Even for small things to now the why is important. What was the motivation for that commit and even to get more complete data a small description of what was made and the results of that.
