### ISSUE TITLE
Share valuable code

### ISSUE THREAD

**Issue by tOOnPT** [tostasqb/tracker#11]
Why not make more use of gitignore? I saw at least one file that didn't make sense to me to be shared with this project files, can you think a bit and tell me what that file is?

**Comment by tostasqb** [comment]
Can't really see what else to ignore here. Maybe the `.editorconfig` or the `rubocop.yml`?

**Comment by tOOnPT** [comment]
Yes. At least that `.editorconfig` shouldn't be there. It isn't part of the project.
