### ISSUE TITLE
do you care about git history?

### ISSUE THREAD

**Issue by lamuria** [tostasqb/tracker#2]
What are your thoughts about git history?

**Comment by tostasqb** [comment]
Git history is pretty important. Although the first commits on any new project don't usually focus on a single feature development, there will be a time where you are not only concerned with saving your work, you'll want to be aware of what you have done in the past, feature or version wise. The importance increases as people working on the same project does too. A good flow would be to make a branch for each new feature developed or to resolve a new bug. 

I like to work with [SourceTree](https://www.sourcetreeapp.com/) for this.

**Comment by lamuria** [comment]
👍 thanks @tostasqb

**Comment by lamuria** [comment]
I'll close this one
