### ISSUE TITLE
logic on controller

### ISSUE THREAD

**Issue by lamuria** [tostasqb/tracker#3]
Why do you have logic on controllers? is that valuable?

Imagine that now you would need to implement a cli interface to your app. What are the changes that you need to do? (you don't need to implement nothing, just describe me the changes)

**Comment by tostasqb** [comment]
I had to search for cli interface development, I knew nothing about, cool beans, thanks! 

Logic on controllers is the way I learned RoR, but that's not an excuse :) I sure believe (but I'm not the best practitioner) in solid'ish development and project organisation. Anyhow, for me, simple projects deserve simple organisations and that's the reason that logic is on the controller side. It's "confy" too when developing. 

Making changes, I'd say putting this logic in a lib class for it to be more widely available.

**Comment by lamuria** [comment]
yep.. unfortunately the way you learned RoR is the way most people learned as well. btw.. the important thing here is that despite your code organization you are aware of this. However, it got me rather curious about one thing, why did you choose to do the challenge in the "rails way" ?
