### ISSUE TITLE
why do you have this distinction on `User` and `Changes`?

### ISSUE THREAD

**Issue by lamuria** [tostasqb/tracker#5]
Why do you have this distinction on `User` and `Changes`? why did you find that valuable?

**Comment by tostasqb** [comment]
Not sure I understood the question. But I'll try to develop on it anyways. Changes is meant to be used with more than one model, like in a [imageable example](http://guides.rubyonrails.org/association_basics.html#polymorphic-associations). So with more than one model, and in a single app use at least, I see this evolving to be a polymorphic association. 

Does this answer your question?

**Comment by lamuria** [comment]
yes, completely 👍
