### ISSUE TITLE
changesController tests

### ISSUE THREAD

**Issue by lamuria** [tostasqb/tracker#7]
[here](https://github.com/tostasqb/tracker/blob/master/spec/controllers/changes_controller_spec.rb) you have the following code:

```ruby
require 'rails_helper'

RSpec.describe ChangesController, type: :controller do
  describe 'GET #list' do
    it 'responds successfully with an HTTP 200 status code' do
      get :list, params: { from: Date.today.to_s, to: Date.today.to_s }, format: 'json'

      expect(response).to be_success
      expect(response).to have_http_status(200)
      expect(response).to render_template(partial: '_list')
    end
  end
end
```

what are you really testing here? do you think there are some missing scenarios?

**Comment by tostasqb** [comment]
Sure. I see maybe calling the `list` method with no arguments at all. And see it failing too.

I have to say, I'm still figuring out testing and the best practice that I should use, I see discussions about BDD and TDD and about how writing testing for non real cases are somehow important for some people (and companies) and not for others with divergent bright opinions on the same subject.  

My take on it for now is that I try (less than I should) to make tests that will simulate more closely the real usage. I guess here I expect both parameters to be always required so didn't test without them.

Surely would like to have your take on this.

**Comment by lamuria** [comment]
I personally think that we should test real use cases. and usually the humans are dumbs.. and the clients of your API will perform the requests without parameters (this will happen for sure), so.. I think at the api level we should test everything we can to simulate the client requests.
