### ISSUE TITLE
what are your thoughts about unit tests?

### ISSUE THREAD

**Issue by lamuria** [tostasqb/tracker#8]
what are your thoughts about unit tests?

[here](https://github.com/tostasqb/tracker/blob/master/app/controllers/users_controller.rb) you have the `submit_diffs` and `discover_diffs` do you think that could be valuable to have tests for these 2functions?

**Comment by tostasqb** [comment]
Definitely. 

My first thoughts on this was to go to stackoverflow and see how people are testing private controller methods. If you would, please [see this](http://stackoverflow.com/questions/4271696/rspec-rails-how-to-test-private-methods-of-controllers), I can relate to each one of the first 4 comments on the question...specially the last one.

Today, looking at that code, and wanting to test it, I would probably transfer `submit_diffs` to the `Change` model and the `discover_diffs`to a new class.
