### ISSUE TITLE
Call an external service

### ISSUE THREAD

**Issue by claudiaalves** [tostasqb/tracker#9]
Imagine that every time it has new changes you need to call an external service. How do you do?

**Comment by tostasqb** [comment]
There's a big take ([example](https://blog.engineyard.com/2014/keeping-your-rails-controllers-dry-with-services)) on how we should manage this type of code and where it belongs. I guess I would try to isolate all external services in a `services` folder below the `app`folder and consume everything from there.

Does this answer your question?

**Comment by claudiaalves** [comment]
Not exactly. I'm trying be more explicit. Imagine that calls take a long time and have impact for the entire application, how do you deal with this?

**Comment by tostasqb** [comment]
Queuing a background process like [sidekiq](https://github.com/mperham/sidekiq) could do the trick, or [faraday](https://github.com/lostisland/faraday) if thinking of an async request.
